import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "../styles/globals.css";

const kanit = Kanit({
  weight: ["400", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.variable}>
        <div className="container max-w-[1320px] mx-auto">{children}</div>
      </body>
    </html>
  );
}
